In [3]:
import numpy as np
import pandas as pd

In [4]:
s = pd.Series([10, 20, 30, 40, 50])

In [5]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
g = np.random.default_rng()

In [7]:
g.integers(0, 100, 10)

array([98,  8, 94, 20, 65, 69, 11, 97, 54, 51])

In [8]:
g.integers(0, 100, 10)

array([74, 82, 44, 31, 76, 43, 54, 90,  3, 54])

In [9]:
g = np.random.default_rng(0)

In [10]:
g.integers(0, 100, 10)

array([85, 63, 51, 26, 30,  4,  7,  1, 17, 81])

In [12]:
g = np.random.default_rng(0)
g.integers(0, 100, 10)

array([85, 63, 51, 26, 30,  4,  7,  1, 17, 81])

In [14]:
s = pd.Series(g.integers(70, 101, 10))
s.index = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()

In [15]:
s

Sep     90
Oct     98
Nov     85
Dec     88
Jan    100
Feb     92
Mar     89
Apr     86
May     87
Jun     98
dtype: int64

In [16]:
months = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s2 = pd.Series(g.integers(70, 101, 10), index=months)

In [17]:
s2

Sep    78
Oct    95
Nov    90
Dec    70
Jan    82
Feb    96
Mar    87
Apr    71
May    93
Jun    92
dtype: int64

In [18]:
print(f"average: {s2.mean()}")

average: 85.4
